Initial commit
KAIR-RoboLab/mater_ros pull request #1
Opened 2023-03-19 22:41 UTC by Kotochleb

2023-03-20 09:04 UTC, macmacal requested changes
Almost LGTM. Only one thread to resolve. After that it will be ready to be merged :+1:

2023-03-20 09:04 UTC, macmacal commented on muter_ros/muter_bringup/launch/bringup.launch.py
> +    rviz2_node = Node(
Suggestion: instead of preparing (another) node description for rviz2 we can use IncludeLaunchDescription for the `rviz.launch.py` launch file.

2023-03-21 09:43 UTC, Kotochleb commented on muter_ros/muter_bringup/launch/bringup.launch.py
> +    rviz2_node = Node(
Done

2023-03-21 10:42 UTC, macmacal commented on muter_ros/muter_bringup/launch/bringup.launch.py
> +    rviz2_node = Node(
Solved

2023-03-21 10:42 UTC, macmacal commented
LGTM :+1:

2023-03-21 10:43 UTC, merged